name: Artillery Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Artillery Tests
        run: |
          artillery run fresh_art.yml --output fresh_art.json && artillery report fresh_art.json --output index.html
      - name: Publish HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: artillery-fresh-report
          path: index.html
